### ISSUE TITLE
Saturn L2 WebUI - Walking Skeleton

### ISSUE THREAD

**Issue by bajtos** [filecoin-project/filecoin-station#23]
1. A new GitHub repo with a LICENSE, with issues & projects enabled, teams & permissions configured, etc.
2. Frontend infrastructure, including minimal infra for testing (Vitest, in-browser testing?)
3. CI/CD process, including a semi-automated process for publishing new versions to the npm registry and a semi-automated process for pulling this new release into the saturn-l2 repo.
4. Rework saturn-l2 HTTP server to serve this new WebUI instead of the dummy HTML page.
5. A minimal Developer Guide: architecture overview, how to set up the dev env, how to make changes, how to run the tests, etc.

**Comment by guanzo** [comment]
> pulling this new release into the saturn-l2 repo

What does this mean exactly? Committing an archive file that contains the HTML/CSS/JS to the l2 repo? Or using something like https://pkg.go.dev/embed?

I took a look at how go-ipfs does it, they just reference the CID of the webui release and download it at runtime. That's easier for go-ipfs since it's an ipfs node, the L2 isn't.

**Comment by bajtos** [comment]
Sorry for not responding earlier.

Downloading the frontend assets from GitHub Releases and embedding them into go binary sounds like a perfect solution to me 👍🏻

**Comment by guanzo** [comment]
Np. This is done.
